import vid1 from "./Videos/one.mp4";
import vid2 from "./Videos/two.mp4";
import vid3 from "./Videos/three.mp4";
import vid4 from "./Videos/four.mp4";

const users = [
  {
    login: "mojombo",
    id: 1,
    avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "defunkt",
    id: 2,
    avatar_url: "https://avatars.githubusercontent.com/u/2?v=4",
    latest_msg: "",
    time: "",
    status: [vid2],
  },
  {
    login: "pjhyett",
    id: 3,
    avatar_url: "https://avatars.githubusercontent.com/u/3?v=4",
    latest_msg: "",
    time: "",
    status: [vid3],
  },
  {
    login: "wycats",
    id: 4,
    avatar_url: "https://avatars.githubusercontent.com/u/4?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "ivey",
    id: 5,
    avatar_url: "https://avatars.githubusercontent.com/u/6?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "vanpelt",
    id: 6,
    avatar_url: "https://avatars.githubusercontent.com/u/17?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },

  {
    login: "wayneeseguin",
    id: 7,
    avatar_url: "https://avatars.githubusercontent.com/u/18?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "brynary",
    id: 8,
    avatar_url: "https://avatars.githubusercontent.com/u/19?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "kevinclark",
    id: 9,
    avatar_url: "https://avatars.githubusercontent.com/u/20?v=4",
    latest_msg: "",
    time: "",
    status: [vid1],
  },
  {
    login: "technoweenie",
    id: 10,
    avatar_url: "https://avatars.githubusercontent.com/u/21?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "macournoyer",
    id: 11,
    avatar_url: "https://avatars.githubusercontent.com/u/22?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "takeo",
    id: 12,
    avatar_url: "https://avatars.githubusercontent.com/u/23?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "anotherjesse",
    id: 13,
    avatar_url: "https://avatars.githubusercontent.com/u/27?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "roland",
    id: 14,
    avatar_url: "https://avatars.githubusercontent.com/u/28?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "tomtt",
    id: 15,
    avatar_url: "https://avatars.githubusercontent.com/u/31?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "nitay",
    id: 16,
    avatar_url: "https://avatars.githubusercontent.com/u/34?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "jamesgolick",
    id: 17,
    avatar_url: "https://avatars.githubusercontent.com/u/37?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "atmos",
    id: 18,
    avatar_url: "https://avatars.githubusercontent.com/u/38?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "mojodna",
    id: 19,
    avatar_url: "https://avatars.githubusercontent.com/u/45?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
  {
    login: "bmizerany",
    id: 20,
    avatar_url: "https://avatars.githubusercontent.com/u/46?v=4",
    latest_msg: "",
    time: "",
    status: [vid4],
  },
];
export default users;
